#  ========================================================================
#   JANUS      Speech- to Speech Translation
#              ------------------------------------------------------------
#              Object: Makefile
#              ------------------------------------------------------------
#
#   Author  :  Christian Fuegen (fuegen@ira.uka.de)
#   Module  :  Makefile.sd
#   Date    :  $Id: Makefile.sd 2390 2003-08-14 11:20:32Z fuegen $
#
#   Remarks :  Default Makefile for all subdirs
#
#  ========================================================================
#
#   This software was developed by
#
#   the  University of Karlsruhe       and  Carnegie Mellon University
#        Dept. of Informatics               Dept. of Computer Science
#        ILKD, Lehrstuhl Prof.Waibel        Alex Waibel's NN & Speech Group
#        Am Fasanengarten 5                 5000 Forbes Ave
#        D-76131 Karlsruhe                  Pittsburgh, PA 15213
#        - West Germany -                   - USA -
#
#   This software is part of the JANUS Speech- to Speech Translation Project
#
#   USAGE PERMITTED ONLY FOR MEMBERS OF THE JANUS PROJECT
#   AT CARNEGIE MELLON UNIVERSITY OR AT UNIVERSITAET KARLSRUHE
#   AND FOR THIRD PARTIES ONLY UNDER SEPARATE WRITTEN PERMISSION
#   BY THE JANUS PROJECT
#
#   It may be copied  only  to members of the JANUS project
#   in accordance with the explicit permission to do so
#   and  with the  inclusion  of  the  copyright  notices.
#
#   This software  or  any  other duplicates thereof may
#   not be copied or otherwise made available to any other person.
#
#   No title to and ownership of the software is hereby transferred.
#
#  ========================================================================
#
#  $Log$
#  Revision 1.2  2003/08/14 11:19:48  fuegen
#  Merged changes on branch jtk-01-01-15-fms (jaguar -> ibis-013)
#
#  Revision 1.1.2.2  2002/06/28 09:52:16  fuegen
#  new Makefiles are now working also on SUN
#
#  Revision 1.1.2.1  2002/06/26 10:09:30  fuegen
#  new Makefiles for JANUS
#
#
#
#  ========================================================================

_SOURCES := $(notdir $(filter $(SRCDIR)/%,$(SOURCES)))
OBJECTS  := $(foreach file,$(_SOURCES:%.c=%.o),../$(OBJDIR)/$(file))
DEPENDS  := $(OBJECTS:%.o=%.d)

# do not print executed commands for making the dependencies
.SILENT: $(DEPENDS)

# targets
janus: $(OBJECTS)

# rule for making the dependencies (taken out of gcc make docu)
../$(OBJDIR)/%.d: %.c
	set -e; $(CC) $(DEPARG) $(ALL_CFLAGS) $< \
	  | sed 's/\($*\)\.o[ :]*/\.\.\/$(OBJDIR)\/\1.o $(subst /,\/,$@) : /g' > $@; \
	  [ -s $@ ] || rm -f $@

-include $(DEPENDS)

# rule for compiling
../$(OBJDIR)/%.o: %.c
	$(CC) -c $(ALL_CFLAGS) $< -o $@
